import{a as L,i as u,S as b}from"./assets/vendor-64b55ca9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=i(t);fetch(t.href,s)}})();async function m(e,o){const i="42361876-39dc0f6de1023fb2a8c585c35",s="https://pixabay.com/api/",n={key:i,q:e,image_type:"photo",orientation:"horizontal",per_page:15,page:o,safesearch:!0};try{const d=await L.get(s,{params:n});return d.data.hits.length===0&&u.show({position:"topRight",messageColor:"white",progressBar:!1,backgroundColor:"red",closeOnClick:!0,close:!1,message:"😭 Sorry, there are no images matching youre search query. Please, try again!"}),d.data}catch(d){throw d}}const w=document.querySelector(".gallery");function v(e){return`<li class="gallery-item">
        <a href="${e.largeImageURL}"> <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
        <div class='discription'><p><b>Likes </b>${e.likes}</p>
        <p><b>Views </b>${e.views}</p>
        <p><b>Comments </b>${e.comments}</p>
        <p><b>Downloads </b>${e.downloads}</p>
        </div>
      </li>`}function f(e){const o=e.hits.map(v).join("");w.insertAdjacentHTML("beforeend",o);const i={captionsData:"alt",captionDelay:250},r=new b(".gallery a",i);r.on("show.simplelightbox"),r.refresh()}const C=document.querySelector("form"),g=document.querySelector(".gallery"),p=document.querySelector(".btn-load-more"),a=document.querySelector(".loader");C.addEventListener("submit",O);p.addEventListener("click",B);let l,c,h;async function O(e){if(e.preventDefault(),a.classList.add("is-open"),c=1,l=e.target.elements.search.value.trim(),g.innerHTML="",l==="")a.classList.remove("is-open"),g.innerHTML="",u.show({position:"topRight",messageColor:"white",progressBar:!1,backgroundColor:"red",closeOnClick:!0,close:!1,message:"❌ Please enter a search tag"});else{const o=await m(l,c);h=Math.ceil(o.totalHits/15),f(o),a.classList.remove("is-open"),y(),e.target.reset()}}async function B(){if(c+=1,a.classList.add("is-open"),l==="")a.classList.remove("is-open"),g.innerHTML="",u.show({position:"topRight",messageColor:"white",progressBar:!1,backgroundColor:"red",closeOnClick:!0,close:!1,message:"❌ Please enter a search tag"});else{const e=await m(l,c);f(e),a.classList.remove("is-open"),y();const o=g.firstElementChild.getBoundingClientRect().height;scrollBy({behavior:"smooth",top:o*2})}}function E(){p.classList.add("hidden")}function P(){p.classList.remove("hidden")}function y(){c>=h?(E(),u.show({position:"topRight",messageColor:"white",progressBar:!1,backgroundColor:"blue",closeOnClick:!0,close:!1,message:"We're sorry, but you've reached the end of search results"})):P()}
//# sourceMappingURL=commonHelpers.js.map
