import{a as w,i as g,S as v}from"./assets/vendor-64b55ca9.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();async function p(e,s){const i="42361876-39dc0f6de1023fb2a8c585c35",o="https://pixabay.com/api/",n={key:i,q:e,image_type:"photo",orientation:"horizontal",per_page:15,page:s,safesearch:!0};try{const d=await w.get(o,{params:n});return d.data.hits.length===0&&g.show({position:"topRight",messageColor:"white",progressBar:!1,backgroundColor:"red",closeOnClick:!0,close:!1,message:"😭 Sorry, there are no images matching youre search query. Please, try again!"}),d.data}catch(d){throw d}}const C=document.querySelector(".gallery");function E(e){return`<li class="gallery-item">
        <a href="${e.largeImageURL}"> <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
        <div class='discription'><p><b>Likes </b>${e.likes}</p>
        <p><b>Views </b>${e.views}</p>
        <p><b>Comments </b>${e.comments}</p>
        <p><b>Downloads </b>${e.downloads}</p>
        </div>
      </li>`}function f(e){const s=e.hits.map(E).join("");C.insertAdjacentHTML("beforeend",s);const i={captionsData:"alt",captionDelay:250},r=new v(".gallery a",i);r.on("show.simplelightbox"),r.refresh()}const O=document.querySelector("form"),u=document.querySelector(".gallery"),m=document.querySelector(".btn-load-more"),a=document.querySelector(".loader");O.addEventListener("submit",$);m.addEventListener("click",P);let c,l,h;async function $(e){if(e.preventDefault(),a.classList.add("is-open"),l=1,c=e.target.elements.search.value.trim(),u.innerHTML="",c==="")a.classList.remove("is-open"),y(),u.innerHTML="",b("❌ Please enter a search tag");else{const s=await p(c,l);h=Math.ceil(s.totalHits/15),f(s),a.classList.remove("is-open"),L(),e.target.reset()}}async function P(){if(l+=1,a.classList.add("is-open"),c==="")a.classList.remove("is-open"),u.innerHTML="",b("❌ Please enter a search tag");else{const e=await p(c,l);f(e),a.classList.remove("is-open"),L();const s=u.firstElementChild.getBoundingClientRect().height;scrollBy({behavior:"smooth",top:s*2})}}function y(){m.classList.add("hidden")}function M(){m.classList.remove("hidden")}function L(){l>=h?(y(),q("We're sorry, but you've reached the end of search results")):M()}function b(e){g.show({title:"",message:`${e}`,position:"topRight",messageColor:"white",closeOnClick:!0,close:!1,backgroundColor:"red"})}function q(e){g.show({title:"",message:`${e}`,position:"topRight",messageColor:"white",closeOnClick:!0,close:!1,backgroundColor:"green"})}
//# sourceMappingURL=commonHelpers.js.map
